### PR TITLE
Upgrade python code to 1.1

### PR DESCRIPTION
**Pull request by askmish**
Signed-off-by: Ashish Kumar Mishra <ashish.k.mishra@intel.com>

### CODE REVIEW

**Comment by danintel** [comment]
This fixes #39.

**Review by danintel — APPROVED** [review]

**Review by danintel — APPROVED** [review]

**Review by danintel — CHANGES_REQUESTED** [review]
Please update "1.0" to "1.1" in README.md under the "Introduction" section.

**Comment by askmish** [comment]
Please review PR#45 which takes over this PR. Hence, closing.

**Comment by danintel** [comment]
#45 link above is not live
https://github.com/askmish/sawtooth-simplewallet/pull/45

**Pull request closed without merging**
