### PR TITLE
README Corrections

### PR DESCRIPTION
**Pull request by danintel**
1. Update supported Transaction Family languages

2. Fix comment for Jack's wallet

3. Minor capitalization changes

Signed-off-by: danintel <daniel.anderson@intel.com>

### CODE REVIEW

**Comment by danintel** [comment]
After I made my changes, I see that the changes in PR #6 are a proper subset of this PR.
I can remerge if PR #6 is integrated before this PR.

**Comment by askmish** [comment]
Hi Dan, Thanks for your contribution. Everything in PR looks good. Since, the PR#6 has been merged and now your commit would have conflicts. Could you address and push again. 

Also, while you're editing it already, could you remove JS from lines 82,83 - we now have JS Client PR and prasad is working on JS TP.

**Comment by danintel** [comment]
I merged PR #6 and removed JS from lines 82,83 as requested.

**Review by askmish — APPROVED** [review]

**Comment by askmish** [comment]
Thanks for the updates.

**Pull request merged**
