### PR TITLE
fixed inconsistencies in the command line examples

### PR DESCRIPTION
**Pull request by jakepanter**

### CODE REVIEW

**Review by maxmijn — DISMISSED** [review]
Simple but good changes.

**Comment by askmish** [comment]
Hi jakepanter, Thanks for your contribution. Could you add a dco sign-off in your commit message. Like so:
`Signed-off-by: your_name<your_github_mail_id>`

**Comment by jakepanter** [comment]
hey askmish, I added the sign-off. thanks for your message!

**Review by danintel — APPROVED** [review]
Looks good. The Signed-off-by is also there.

**Review by askmish — APPROVED** [review]

**Pull request merged**
